### ISSUE TITLE
Base image 1.2.1 came from now has package vulnerabilities - still present in latest version

### ISSUE THREAD

**Issue by garadox** [fabric8io-images/jetty#2]
Can you please publish an updated tag with just a run of the docker build? It should pull in the latest package updates and remove some vulnerabilities present in openjdk 8u111, and others.

**Comment by rhuss** [comment]
Thanks for the heads up, I just made an update of the dependencies (agent-bond, run-java.sh), too and triggered a 1.3.0 build.

**Comment by garadox** [comment]
Thanks for the quick response!
